# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Informacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Informacion(object):
    def setupUi(self, Informacion):
        Informacion.setObjectName("Informacion")
        Informacion.resize(501, 428)
        Informacion.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.centralwidget = QtWidgets.QWidget(Informacion)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 20, 424, 339))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.dni = QtWidgets.QLineEdit(self.widget)
        self.dni.setObjectName("dni")
        self.gridLayout.addWidget(self.dni, 2, 2, 1, 1)
        self.Buscar = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Buscar.setFont(font)
        self.Buscar.setObjectName("Buscar")
        self.gridLayout.addWidget(self.Buscar, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 3)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget, 5, 0, 1, 3)
        Informacion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Informacion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        Informacion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Informacion)
        self.statusbar.setObjectName("statusbar")
        Informacion.setStatusBar(self.statusbar)

        self.retranslateUi(Informacion)
        QtCore.QMetaObject.connectSlotsByName(Informacion)

    def retranslateUi(self, Informacion):
        _translate = QtCore.QCoreApplication.translate
        Informacion.setWindowTitle(_translate("Informacion", "Informacion"))
        self.label_3.setText(_translate("Informacion", "INFORMACION  MEDICOS DE PLANTA"))
        self.label_2.setText(_translate("Informacion", "Ingrese dni"))
        self.Buscar.setText(_translate("Informacion", "Buscar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Informacion", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Informacion", "Especialidad"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Informacion", "Dni"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Informacion", "Hospital"))
