# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfazHospital.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hospital(object):
    def setupUi(self, Hospital):
        Hospital.setObjectName("Hospital")
        Hospital.resize(417, 207)
        Hospital.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.centralwidget = QtWidgets.QWidget(Hospital)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 391, 131))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.NombreHospital = QtWidgets.QLineEdit(self.widget)
        self.NombreHospital.setObjectName("NombreHospital")
        self.gridLayout.addWidget(self.NombreHospital, 0, 1, 1, 1)
        self.AgregarHospital = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AgregarHospital.setFont(font)
        self.AgregarHospital.setObjectName("AgregarHospital")
        self.gridLayout.addWidget(self.AgregarHospital, 1, 1, 1, 1)
        Hospital.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Hospital)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 21))
        self.menubar.setObjectName("menubar")
        Hospital.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Hospital)
        self.statusbar.setObjectName("statusbar")
        Hospital.setStatusBar(self.statusbar)

        self.retranslateUi(Hospital)
        QtCore.QMetaObject.connectSlotsByName(Hospital)

    def retranslateUi(self, Hospital):
        _translate = QtCore.QCoreApplication.translate
        Hospital.setWindowTitle(_translate("Hospital", "MainWindow"))
        self.label.setText(_translate("Hospital", "Nombre de Hospital"))
        self.AgregarHospital.setText(_translate("Hospital", "Guardar"))
